#!/usr/bin/env bash
set -ex

# USE HOMEBREW VERSION OF LLVM/CLANG!

CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
# LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
LDFLAGS="-L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib -lunwind"
PATH="/opt/homebrew/opt/llvm/bin:$PATH"

clang \
    --target=wasm32 \
    -nostdlib \
    -mbulk-memory \
    -O3 \
    -Wl,--no-entry \
    -Wl,--allow-undefined \
    -Wl,--import-memory \
    -Wl,--stack-first \
    -o test.wasm \
    test.c

{ set +x; } 2> /dev/null
echo "SUCCESS:"
wasm2wat test.wasm

    # -Wl,--lto-O3 \
