#!/usr/bin/env python3

from subprocess import run
from os.path import dirname, abspath

DIR = dirname(abspath(__file__))
def RUN(cmd, path=DIR):
    print("========================")
    print(cmd.replace("\\", "\n"), end="")
    print("========================")
    run(cmd, shell=True, cwd=path)

RUN(
    "emcc                                       \\"
    "test.c                                     \\"
    "-v                                         \\"
    "--no-entry                                 \\"
    "-s EXPORTED_FUNCTIONS=\"['_add']\"         \\"
    # "-Os                                        \\"
    "-o test.wasm                               \\"
)







# RUN("""
# clang \
#     --target=wasm32 \
#     -nostdlib \
#     -O3 \
#     -o test.wasm \
#     test.c
# """)


# #!/bin/bash
# set -e

# clang++ \
#     --target=wasm32 \
#     -nostdlib \
#     -O3 \
#     -o /tmp/inc.o \
#     -c \
#     inc.cpp

# wasm-ld \
#     --no-entry \
#     --export-all \
#     --lto-O3 \
#     --allow-undefined \
#     --import-memory \
#     /tmp/inc.o \
#     -o inc.wasm

# rm -rf inc.wasm.tmp*
# hexdump inc.wasm | head -n 1
