#!/usr/bin/env bash
#
# Build C code to WebAssembly
#
# Prerequisite: (Xcode clang doesn't have wasm32 target)
#     brew install llvm
# Optional: (for wasm2wat, showing wasm text format)
#     brew install wabt
#
set -ex

# SETUP
IN="z85.c"
OUT="../../02_DEPLOY/wasm/z85.wasm"

# USE HOMEBREW VERSION OF LLVM/CLANG!
CFLAGS="${CFLAGS} -I/opt/homebrew/opt/llvm/include"
CPPFLAGS="${CPPFLAGS} -I/opt/homebrew/opt/llvm/include"
LDFLAGS="${LDFLAGS} -L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib -lunwind"
PATH="/opt/homebrew/opt/llvm/bin:$PATH"

# BUILD IT!
clang \
    --target=wasm32 \
    -std=c23 \
    -fcolor-diagnostics \
    -nostdlib \
    -mbulk-memory \
    -O3 \
    -Wl,--no-entry \
    -Wl,--allow-undefined \
    -Wl,--import-memory \
    -Wl,--stack-first \
    -o $OUT \
    $IN

# SUCCESS AND OUTPUT
{ set +x; } 2> /dev/null
# printf "\x1b[0m"  # reset
printf "\x1b[32m" # set green
echo "SUCCESS:"
printf "\x1b[0m"  # reset
wasm2wat $OUT

# DISCARDED OPTIONS
    # -Wl,--lto-O3 \
